# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 818c8ca8b8ed170d4bb75553228bbfe874377c6bc886f7488b288556634b6e524ad78c144776131a5c5e5703e32aa5d67aa69e9f778830ff2714d81ea3d852fa

test:
  secret_key_base: 069ce8d6bf540a8f9833b996bd2f4e019d130a888201e0c177eef43b9e6577b79cc7b4bd8d57194830c14134f0cca71c032a7ca4a4d04915a897ff8cd2583b7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
